name: Update docs

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    - name: Install VuePress
      run: npm install -g vuepress

    - name: Install Dependencies
      run: npm install

    - name: Generate Static Files
      run: vuepress build docs
    - name: CNMAE
      run: echo "hexoplusplus.js.org" > docs/.vuepress/dist/CNAME
    - name: GoogleSearch
      run: |
        mv ./google270a4bc486b01c41.html  google270a4bc486b01c41.html
        mv ./ads.txt ./docs/.vuepress/dist/ads.txt

    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: docs/.vuepress/dist
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
